language: rust
cache: cargo
rust:
- nightly
- beta
- stable
- 1.19.0
branches:
  only:
    - staging
    - trying
    - master
after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  [ $TRAVIS_RUST_VERSION = stable ] &&
  which mdbook || cargo install mdbook &&
  cd book &&
  mdbook build &&
  cd ..
deploy:
  provider: pages
  local_dir: "book/book"
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
    condition: "$TRAVIS_RUST_VERSION = stable"
